title:              James Darling
email:              james@abscond.org
author:             James Darling
baseurl:            "/"
url:                "https://abscond.org"

# Social Profiles
twitter_username:   abscond
github_username:    james
facebook_username:  jamesdarling
instagram_username:  abscond
linkedin_username: abscond

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
