title:              James Darling
email:              james@abscond.org
author:             James Darling
url:                "https://abscond.org"
sass:
    sass_dir: ./assets

# Build settings
markdown:           kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

jekyll-archives:
  enabled: 
    - tags
  layout: tag
